### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'docker': 'docker' when running docker-compose up

### ISSUE THREAD

**Issue by martinburchell** [getporter/docker-compose-mixin#28]
I've seen this when trying to install my own bundle and also with the examples:
```

[16:56:51 workspace]$ git clone https://github.com/getporter/docker-compose-mixin.git
Cloning into 'docker-compose-mixin'...
remote: Enumerating objects: 219, done.
remote: Counting objects: 100% (219/219), done.
remote: Compressing objects: 100% (144/144), done.
remote: Total 219 (delta 90), reused 161 (delta 57), pack-reused 0
Receiving objects: 100% (219/219), 99.80 KiB | 1.49 MiB/s, done.
Resolving deltas: 100% (90/90), done.
[16:57:31 workspace]$ cd docker-compose-mixin/
[16:57:36 docker-compose-mixin]$ cd examples/
[16:57:42 examples]$ cd compose/
[16:58:08 compose]$ porter install --allow-docker-host-access
installing compose...
executing install action from compose (installation: compose)
Docker Compose up
Building web
[23] Failed to execute script docker-compose
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1186, in up
  File "compose/cli/main.py", line 1182, in up
  File "compose/project.py", line 664, in up
  File "compose/service.py", line 364, in ensure_image_exists
  File "compose/service.py", line 1133, in build
  File "compose/service.py", line 1943, in build
  File "subprocess.py", line 800, in __init__
  File "subprocess.py", line 1551, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'docker': 'docker'
Error: error running command /cnab/app docker-compose up -d: exit status 255
err: error running command /cnab/app docker-compose up -d: exit status 255
Error: mixin execution failed: exit status 1
Error: 1 error occurred:
        * container exit code: 1, message: <nil>

```

Setup:

Porter: Latest
docker-compose-mixin: v0.4.1
OS: Ubuntu 18.04 (also fails on MacOS Big Sur 11.6)
Docker: 20.10.7 (20.10.8 on MacOS)
docker-compose: 1.29.2, build 5becea4c

**Comment by vdice** [comment]
Hi @martinburchell, thanks for filing this issue.  The 'compose' example bundle indeed needing updating (the `docker` mixin should also be declared under the `mixins` section).  I've put up a PR to fix the example as well as add a section to the README around the necessity of declaring the `docker` mixin for most Docker Compose bundles.

As background, starting with the [v0.4.0](https://github.com/getporter/docker-compose-mixin/releases/tag/v0.4.0) version of this mixin, the `docker` CLI is no longer shipped and must be added separately via its mixin counterpart.  Alas, as you've pointed out, some examples still needed updating and I'm hoping the added documentation will be helpful to guide users.  Apologies for the disruption.  Adding the [docker mixin](https://github.com/getporter/docker-mixin) to your compose bundle should unblock.

**Comment by martinburchell** [comment]
@vdice thanks for the speedy response. Yes that's getting past the FIleNotFoundError now.

**Comment by vdice** [comment]
Oops, I should let https://github.com/getporter/docker-compose-mixin/pull/29 officially close this issue.  Re-opening.
